// Auto-generated — do not edit manually
export const TEAM_CRESTS: Record<string, string> = {
  'Algeria': '/crests/778.svg',
  'Argentina': '/crests/762.png',
  'Australia': '/crests/779.svg',
  'Austria': '/crests/816.svg',
  'Belgium': '/crests/805.svg',
  'Bosnia-H.': '/crests/1060.svg',
  'Bosnia-Herzegovina': '/crests/1060.svg',
  'Brazil': '/crests/764.svg',
  'Canada': '/crests/828.svg',
  'Cape Verde': '/crests/1930.svg',
  'Cape Verde Islands': '/crests/1930.svg',
  'Colombia': '/crests/818.svg',
  'Congo DR': '/crests/1934.svg',
  'Croatia': '/crests/799.svg',
  'Curaçao': '/crests/9460.svg',
  'Czechia': '/crests/798.svg',
  'Ecuador': '/crests/791.svg',
  'Egypt': '/crests/825.svg',
  'England': '/crests/770.svg',
  'France': '/crests/773.svg',
  'Germany': '/crests/759.svg',
  'Ghana': '/crests/763.svg',
  'Haiti': '/crests/836.svg',
  'Iran': '/crests/840.svg',
  'Iraq': '/crests/8062.svg',
  'Ivory Coast': '/crests/1935.svg',
  'Japan': '/crests/766.svg',
  'Jordan': '/crests/8049.png',
  'Korea Republic': '/crests/772.png',
  'Mexico': '/crests/769.svg',
  'Morocco': '/crests/815.svg',
  'Netherlands': '/crests/8601.svg',
  'New Zealand': '/crests/783.svg',
  'Norway': '/crests/8872.svg',
  'Panama': '/crests/1836.svg',
  'Paraguay': '/crests/761.svg',
  'Portugal': '/crests/765.svg',
  'Qatar': '/crests/8030.svg',
  'Saudi Arabia': '/crests/801.svg',
  'Scotland': '/crests/8873.svg',
  'Senegal': '/crests/804.svg',
  'South Africa': '/crests/774.svg',
  'South Korea': '/crests/772.png',
  'Spain': '/crests/760.svg',
  'Sweden': '/crests/792.svg',
  'Switzerland': '/crests/788.svg',
  'Tunisia': '/crests/802.svg',
  'Turkey': '/crests/803.svg',
  'Türkiye': '/crests/803.svg',
  'DR Congo': '/crests/1934.svg',
  "Côte d'Ivoire": '/crests/1935.svg',
  'USA': '/crests/771.svg',
  'United States': '/crests/771.svg',
  'Uruguay': '/crests/758.svg',
  'Uzbekistan': '/crests/8070.png',
}
